[project]
name = "python-template"
version = "0.1.0"
description = "Python Starter Template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "pytest>=8.3.4",
    "ruff>=0.9.9",
]

[tool.pytest.ini_options]
pythonpath = "src"
